---

- name: Delete old files
  when: inventory_hostname in groups['local']
  file:
    state: absent
    path: "{{store_files_path}}/"

- name: Create Directory "{{store_files_path}}" 
  when: inventory_hostname in groups['local']
  file:
    state: directory
    path: "{{store_files_path}}"

- name: Generate a Password for the Public key
  when: inventory_hostname in groups['local']
  shell: pwgen -N 1 -s 30 | tee "{{store_files_path}}/password.txt"

- name: Echoing Password to place as variable
  when: inventory_hostname in groups['local']
  shell: cat "{{store_files_path}}/password.txt"
  register: echoing_passwd

- name: Create Public Key with the password
  when: inventory_hostname in groups['local']
  shell: ssh-keygen -f "{{store_files_path}}/SSH-Key" -t rsa -b 4096 -N "{{echoing_passwd.stdout}}"

- name: Deploy Public Key to the server
  when: inventory_hostname in groups['Servers']
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file','public-key-setup_role/files/SSH-Key.pub') }}"
    